[package]
name = "diesel_demo_step_1_pg"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.0", features = ["postgres", "chrono"] }
dotenv = "0.10"
chrono = "0.4"